on: [push]

concurrency: clean

env:
  PACKAGE_NAME: ghcr-cleaner

jobs:
  container:
    runs-on: ubuntu-latest
    name: Clean testing container registry
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create untagged image
        run: |
          echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

          export IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}:latest
          docker build -t ${IMAGE_NAME} -f test.Dockerfile --build-arg VALUE=1 .
          docker push ${IMAGE_NAME}

          docker build -t ${IMAGE_NAME} -f test.Dockerfile --build-arg VALUE=2 .
          docker push ${IMAGE_NAME}
      - name: Run `ghcr-cleaner` action
        uses: ./
        with:
          githubToken: ${{ secrets.GH_TOKEN }}
          packageName: ${{ env.PACKAGE_NAME }}
          owner: ${{ github.repository_owner }}
          ownerType: user
